FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Le code source est monté via volume, pas copié
# COPY . .  ← pas besoin en dev

EXPOSE 4200

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--poll", "2000"]
